### ISSUE TITLE
NEED HELP

### ISSUE THREAD

**Issue by ASIIMWE1** [mri4all/console#26]
@sairamgeethanath
Running sudo ./install.sh shows this error:
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
error: 3060 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
Kindly help out.

**Comment by sairamgeethanath** [comment]
Please run it from within the folder containing install.sh. 
I will try to reproduce this error locally. 

1. Please make sure your internet connection is stable.
2. Please ensure your git config is clean and does not point to anything residual from previous installations.

**Comment by ASIIMWE1** [comment]
This also worked out yesterday.
